local Math = {}

Math.EPSILON = 0.00001

--[[
A naive implementation that should work ...
]]
function Math.floatEquals(x, y)
    return math.abs(x - y) < Math.EPSILON
end

function Math.initializeRandomSeed()
    -- Source: http://lua-users.org/wiki/MathLibraryTutorial
    math.randomseed( tonumber(tostring(os.time()):reverse():sub(1,6)) )

    -- A bit of superstitious witchcraft. This ought to make it *more* random:
    math.random(); math.random(); math.random()
end

return Math
